### ISSUE TITLE
Solr下，高亮不生效，测试版本4.9 4.91 4.10.3

### ISSUE THREAD

**Issue by cnxobo** [chenlb/mmseg4j-solr#11]
Solr下，高亮不生效，测试版本4.9 4.91 4.10.3

通过solr自带的http://localhost:8983/solr/#/collection1/query做测试。

Solr自带的方式可以正常高亮搜索词。
当把field content的type由text_general改为textComplex后。

能返回搜索结果，但是高亮只有ID没有具体内容

**Comment by chenlb** [comment]
请给出具体的索引内容和搜索内容

**Comment by cnxobo** [comment]
直接搜索关键字 比如 “佛山”， 能找到内容，但是关键字没有高亮。
如果搜索“content:佛山”，返回的结果，既有内容，也有关键字。
我也是随便复制了一篇新闻提交上去的。

第一次用Solr，用法不熟。
目前就通过加前缀的方法，没什么问题。

**Comment by ibazzi** [comment]
最近我也碰到了这个问题。在看了solr的源代码后，发现在查询时没有指定查询的field名，或者没有设置df参数时，会使用默认的field(_text_)，导致关键字的分词结果和内容的分词结果不同。高亮就不会生效。
