### ISSUE TITLE
支持 solr5.0

### ISSUE THREAD

**Issue by bodhi52** [chenlb/mmseg4j-solr#12]
啥时候支持solr5.0呢？

**Comment by xxiu** [comment]
同问啥时候能支持呢

**Comment by chenlb** [comment]
solr 5 年初二发布了，我考虑两周以内支持。

**Comment by Dourm** [comment]
报了null:java.lang.AbstractMethodError: org.apache.lucene.analysis.util.TokenizerFactory.create(Lorg/apache/lucene/util/AttributeFactory;)Lorg/apache/lucene/analysis/Tokenizer;,原来是还不支持5.0啊!

**Comment by wangshiyang** [comment]
5.0还没支持吗？   快了 吧

**Comment by chenlb** [comment]
已经发布 2.3.0 支持 lucene/solr 5.0，下载地址： http://pan.baidu.com/s/1dD7qMFf

**Comment by ArvinC** [comment]
厉害

**Comment by ArvinC** [comment]
请问2.3.0的源码发布到哪了？maven能获取吗

**Comment by chenlb** [comment]
maven 中心库取得到

```xml
<dependency>
    <groupId>com.chenlb.mmseg4j</groupId>
    <artifactId>mmseg4j-solr</artifactId>
    <version>2.3.0</version>
</dependency>
```

http://search.maven.org/#artifactdetails%7Ccom.chenlb.mmseg4j%7Cmmseg4j-solr%7C2.3.0%7Cjar
