### ISSUE TITLE
请问能用在solr6上了吗

### ISSUE THREAD

**Issue by adolfjap** [chenlb/mmseg4j-solr#23]
在solr6上现出 org.apache.solr.common.SolrException: Error loading class 'org.apache.solr.update.processor.LangDetectLanguageIdentifierUpdateProcessorFactory'

**Comment by amao12580** [comment]
提交了PR，支持solr6.1：https://github.com/chenlb/mmseg4j-solr/pull/26

详细说明：http://amao12580.github.io/post/2016/07/mmseg4j-solr-compatible-solr-6-1/

**Comment by chenlb** [comment]
#30 支持 solr 6.x 了。 2.4.0 版本
