### ISSUE TITLE
solr6.1已经不支持getInstanceDir()函数了

### ISSUE THREAD

**Issue by mynextlife** [chenlb/mmseg4j-solr#25]
在solr6.1中，getInstanceDir()已经被换为getInstancePath()，请作者进行升级。
在现有版本中，要避免该函数带来的问题，需要在设置dicpath的时候使用绝对路径，而不要使用相对路径

**Comment by amao12580** [comment]
提交了PR，支持solr6.1：https://github.com/chenlb/mmseg4j-solr/pull/26

详细说明：http://amao12580.github.io/post/2016/07/mmseg4j-solr-compatible-solr-6-1/

**Comment by chenlb** [comment]
#30 支持 solr 6.x 了，2.4.0 版本

**Comment by chenlb** [comment]
@amao12580  由于代码格式不一致。没接入合并。dev-tools 目录加新加入了两上格式模板。后继有兴趣贡献代码，可以使用这个模板。
