### ISSUE TITLE
java.lang.NoSuchMethodError: com.chenlb.mmseg4j.analysis.MMSegTokenizer.<init>(Lcom/chenlb/mmseg4j/Seg;)V

### ISSUE THREAD

**Issue by fmpoffice** [chenlb/mmseg4j-solr#31]
![qq 20170208174043](https://cloud.githubusercontent.com/assets/11001031/22731549/fedc1b44-ee25-11e6-94d7-331734b56df1.png)

神啊！救救我吧！
window + tomcat9 +solr6.3  + mmseg4j-core-1.10.0 + mmseg4j-analysis-1.9.1 + mmseg4j-solr-2.4.0

`
	<field name="search_id" type="string" indexed="false" stored="false"/>
	<field name="product_code" type="long" indexed="true" stored="true"/>
	<field name="raw_title" type="string" indexed="false" stored="false"/>
	<field name="score" type="string" indexed="false" stored="false"/>
	<field name="raws_title" type="aComplex" indexed="true" stored="true"/>
	<field name="product_name" type="aComplex" indexed="true" stored="true"/>
	<field name="changeTime" type="date" indexed="false" stored="false"/>

	<fieldtype name="aComplex" class="solr.TextField" positionIncrementGap="100">
		<analyzer>
			<tokenizer class="com.chenlb.mmseg4j.solr.MMSegTokenizerFactory" mode="complex" dicPath="C:/solr/fenchi"/>
		</analyzer>
	</fieldtype>
	<fieldtype name="aMaxWord" class="solr.TextField" positionIncrementGap="100">
		<analyzer>
			<tokenizer class="com.chenlb.mmseg4j.solr.MMSegTokenizerFactory" mode="max-word" />
		</analyzer>
	</fieldtype>
	<fieldtype name="aSimple" class="solr.TextField" positionIncrementGap="100">
		<analyzer>
			<tokenizer class="com.chenlb.mmseg4j.solr.MMSegTokenizerFactory" mode="simple" dicPath="C:/solr/fenchi"/>
		</analyzer>
	</fieldtype>
`

**Comment by chenlb** [comment]
不用 mmseg4j-analysis-1.9.1。mmseg4j-solr-2.4.0 已经包括了 analysis

经测试 solr-6.3.0 和 solr-6.6.0 没有问题。两个lib 即可

```
mmseg4j-core-1.10.0.jar
mmseg4j-solr-2.4.0.jar
```
