### ISSUE TITLE
没有文档

### ISSUE THREAD

**Issue by gravin** [chenlb/mmseg4j-solr#33]
我只想调用一下对字符串分词一下，可是没有介绍，不知道怎么用，网上也搜不到说明、
难道靠猜？

**Comment by chenlb** [comment]
新版请看：https://github.com/chenlb/mmseg4j-core/tree/master/src/main/java/com/chenlb/mmseg4j/example


以下是老版本的说明，https://github.com/chenlb/mmseg4j-from-googlecode

```
java -jar mmseg4j-core-1.8-with-dic.jar '这里是字符串'

java -cp .;mmseg4j-1.6.jar -Dmmseg.dic.path=./other-dic com.chenlb.mmseg4j.example.Simple '这里是字符串'

java -cp .;mmseg4j-1.6.jar com.chenlb.mmseg4j.example.MaxWord '这里是字符串'
```
